name = "r2-dir-list"
main = "src/index.tsx"
compatibility_date = "2024-04-05"
workers_dev = false

[[routes]]
pattern = "lib.yantaowang.com/*"
zone_name = "yantaowang.com"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "BUCKET_monolibrary"
bucket_name = "monolibrary"

[vars]
PASSWORD = "19881207"
USERNAME = "chenxuelee"
AUTH_SECRET= "20241988"

AUTH_GITHUB_ID = "1baede0f8bee25b11c38"
AUTH_GITHUB_SECRET = "wwuufgw"






